'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace NextSoftService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="COM_Sobrestadia_BE", [Namespace]:="http://schemas.datacontract.org/2004/07/Application.BusinessEntities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class COM_Sobrestadia_BE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecCreaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecModField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrCreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrModField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CONT_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ENTC_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_FecFinField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_FecIniField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_ObservacionesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_ServiceContractField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecCrea() As Date
            Get
                Return Me.AUDI_FecCreaField
            End Get
            Set
                If (Me.AUDI_FecCreaField.Equals(value) <> true) Then
                    Me.AUDI_FecCreaField = value
                    Me.RaisePropertyChanged("AUDI_FecCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecMod() As Date
            Get
                Return Me.AUDI_FecModField
            End Get
            Set
                If (Me.AUDI_FecModField.Equals(value) <> true) Then
                    Me.AUDI_FecModField = value
                    Me.RaisePropertyChanged("AUDI_FecMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrCrea() As String
            Get
                Return Me.AUDI_UsrCreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrCreaField, value) <> true) Then
                    Me.AUDI_UsrCreaField = value
                    Me.RaisePropertyChanged("AUDI_UsrCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrMod() As String
            Get
                Return Me.AUDI_UsrModField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrModField, value) <> true) Then
                    Me.AUDI_UsrModField = value
                    Me.RaisePropertyChanged("AUDI_UsrMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CONT_Codigo() As Integer
            Get
                Return Me.CONT_CodigoField
            End Get
            Set
                If (Me.CONT_CodigoField.Equals(value) <> true) Then
                    Me.CONT_CodigoField = value
                    Me.RaisePropertyChanged("CONT_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ENTC_Codigo() As Integer
            Get
                Return Me.ENTC_CodigoField
            End Get
            Set
                If (Me.ENTC_CodigoField.Equals(value) <> true) Then
                    Me.ENTC_CodigoField = value
                    Me.RaisePropertyChanged("ENTC_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_Activo() As Boolean
            Get
                Return Me.SOES_ActivoField
            End Get
            Set
                If (Me.SOES_ActivoField.Equals(value) <> true) Then
                    Me.SOES_ActivoField = value
                    Me.RaisePropertyChanged("SOES_Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_Codigo() As Integer
            Get
                Return Me.SOES_CodigoField
            End Get
            Set
                If (Me.SOES_CodigoField.Equals(value) <> true) Then
                    Me.SOES_CodigoField = value
                    Me.RaisePropertyChanged("SOES_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_FecFin() As System.Nullable(Of Date)
            Get
                Return Me.SOES_FecFinField
            End Get
            Set
                If (Me.SOES_FecFinField.Equals(value) <> true) Then
                    Me.SOES_FecFinField = value
                    Me.RaisePropertyChanged("SOES_FecFin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_FecIni() As System.Nullable(Of Date)
            Get
                Return Me.SOES_FecIniField
            End Get
            Set
                If (Me.SOES_FecIniField.Equals(value) <> true) Then
                    Me.SOES_FecIniField = value
                    Me.RaisePropertyChanged("SOES_FecIni")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_Observaciones() As String
            Get
                Return Me.SOES_ObservacionesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SOES_ObservacionesField, value) <> true) Then
                    Me.SOES_ObservacionesField = value
                    Me.RaisePropertyChanged("SOES_Observaciones")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_ServiceContract() As String
            Get
                Return Me.SOES_ServiceContractField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SOES_ServiceContractField, value) <> true) Then
                    Me.SOES_ServiceContractField = value
                    Me.RaisePropertyChanged("SOES_ServiceContract")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="COM_DetSobrestadia_BE", [Namespace]:="http://schemas.datacontract.org/2004/07/Application.BusinessEntities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class COM_DetSobrestadia_BE
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecCreaField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_FecModField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrCreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUDI_UsrModField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PACK_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PUER_CodDestinoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_CodigoField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_DiasSobrestadiaClienteField As Short
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SOES_ItemField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecCrea() As Date
            Get
                Return Me.AUDI_FecCreaField
            End Get
            Set
                If (Me.AUDI_FecCreaField.Equals(value) <> true) Then
                    Me.AUDI_FecCreaField = value
                    Me.RaisePropertyChanged("AUDI_FecCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_FecMod() As Date
            Get
                Return Me.AUDI_FecModField
            End Get
            Set
                If (Me.AUDI_FecModField.Equals(value) <> true) Then
                    Me.AUDI_FecModField = value
                    Me.RaisePropertyChanged("AUDI_FecMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrCrea() As String
            Get
                Return Me.AUDI_UsrCreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrCreaField, value) <> true) Then
                    Me.AUDI_UsrCreaField = value
                    Me.RaisePropertyChanged("AUDI_UsrCrea")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUDI_UsrMod() As String
            Get
                Return Me.AUDI_UsrModField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUDI_UsrModField, value) <> true) Then
                    Me.AUDI_UsrModField = value
                    Me.RaisePropertyChanged("AUDI_UsrMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PACK_Codigo() As Integer
            Get
                Return Me.PACK_CodigoField
            End Get
            Set
                If (Me.PACK_CodigoField.Equals(value) <> true) Then
                    Me.PACK_CodigoField = value
                    Me.RaisePropertyChanged("PACK_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PUER_CodDestino() As Integer
            Get
                Return Me.PUER_CodDestinoField
            End Get
            Set
                If (Me.PUER_CodDestinoField.Equals(value) <> true) Then
                    Me.PUER_CodDestinoField = value
                    Me.RaisePropertyChanged("PUER_CodDestino")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_Codigo() As Integer
            Get
                Return Me.SOES_CodigoField
            End Get
            Set
                If (Me.SOES_CodigoField.Equals(value) <> true) Then
                    Me.SOES_CodigoField = value
                    Me.RaisePropertyChanged("SOES_Codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_DiasSobrestadiaCliente() As Short
            Get
                Return Me.SOES_DiasSobrestadiaClienteField
            End Get
            Set
                If (Me.SOES_DiasSobrestadiaClienteField.Equals(value) <> true) Then
                    Me.SOES_DiasSobrestadiaClienteField = value
                    Me.RaisePropertyChanged("SOES_DiasSobrestadiaCliente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SOES_Item() As Integer
            Get
                Return Me.SOES_ItemField
            End Get
            Set
                If (Me.SOES_ItemField.Equals(value) <> true) Then
                    Me.SOES_ItemField = value
                    Me.RaisePropertyChanged("SOES_Item")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="NextSoftService.INextSoftService")>  _
    Public Interface INextSoftService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/ExecuteSQL", ReplyAction:="http://tempuri.org/INextSoftService/ExecuteSQLResponse")>  _
        Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/ExecuteSQL", ReplyAction:="http://tempuri.org/INextSoftService/ExecuteSQLResponse")>  _
        Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/INextSoftService/ExecuteSQLNonQueryResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(NextSoftService.COM_Sobrestadia_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(NextSoftService.COM_DetSobrestadia_BE)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Object()))>  _
        Function ExecuteSQLNonQuery(ByVal QueryString As String) As Object()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/ExecuteSQLNonQuery", ReplyAction:="http://tempuri.org/INextSoftService/ExecuteSQLNonQueryResponse")>  _
        Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/InsertSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/InsertSobrestadiaResponse")>  _
        Function InsertSobrestadia(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/InsertSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/InsertSobrestadiaResponse")>  _
        Function InsertSobrestadiaAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/UpdateSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/UpdateSobrestadiaResponse")>  _
        Function UpdateSobrestadia(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/UpdateSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/UpdateSobrestadiaResponse")>  _
        Function UpdateSobrestadiaAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/DeleteSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/DeleteSobrestadiaResponse")>  _
        Function DeleteSobrestadia(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/DeleteSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/DeleteSobrestadiaResponse")>  _
        Function DeleteSobrestadiaAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/GetAllSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/GetAllSobrestadiaResponse")>  _
        Function GetAllSobrestadia(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As NextSoftService.COM_Sobrestadia_BE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/GetAllSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/GetAllSobrestadiaResponse")>  _
        Function GetAllSobrestadiaAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of NextSoftService.COM_Sobrestadia_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/GetSobrestadiaByFilter", ReplyAction:="http://tempuri.org/INextSoftService/GetSobrestadiaByFilterResponse")>  _
        Function GetSobrestadiaByFilter(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/GetSobrestadiaByFilter", ReplyAction:="http://tempuri.org/INextSoftService/GetSobrestadiaByFilterResponse")>  _
        Function GetSobrestadiaByFilterAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/InsertDetSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/InsertDetSobrestadiaResponse")>  _
        Function InsertDetSobrestadia(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/InsertDetSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/InsertDetSobrestadiaResponse")>  _
        Function InsertDetSobrestadiaAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/UpdateDetSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/UpdateDetSobrestadiaResponse")>  _
        Function UpdateDetSobrestadia(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/UpdateDetSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/UpdateDetSobrestadiaResponse")>  _
        Function UpdateDetSobrestadiaAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/DeleteDetSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/DeleteDetSobrestadiaResponse")>  _
        Function DeleteDetSobrestadia(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/DeleteDetSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/DeleteDetSobrestadiaResponse")>  _
        Function DeleteDetSobrestadiaAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/GetAllDetSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/GetAllDetSobrestadiaResponse")>  _
        Function GetAllDetSobrestadia(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As NextSoftService.COM_DetSobrestadia_BE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/GetAllDetSobrestadia", ReplyAction:="http://tempuri.org/INextSoftService/GetAllDetSobrestadiaResponse")>  _
        Function GetAllDetSobrestadiaAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of NextSoftService.COM_DetSobrestadia_BE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/GetDetSobrestadiaByFilter", ReplyAction:="http://tempuri.org/INextSoftService/GetDetSobrestadiaByFilterResponse")>  _
        Function GetDetSobrestadiaByFilter(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INextSoftService/GetDetSobrestadiaByFilter", ReplyAction:="http://tempuri.org/INextSoftService/GetDetSobrestadiaByFilterResponse")>  _
        Function GetDetSobrestadiaByFilterAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface INextSoftServiceChannel
        Inherits NextSoftService.INextSoftService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class NextSoftServiceClient
        Inherits System.ServiceModel.ClientBase(Of NextSoftService.INextSoftService)
        Implements NextSoftService.INextSoftService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements NextSoftService.INextSoftService.ExecuteSQL
            Return MyBase.Channel.ExecuteSQL(QueryString)
        End Function
        
        Public Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements NextSoftService.INextSoftService.ExecuteSQLAsync
            Return MyBase.Channel.ExecuteSQLAsync(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQuery(ByVal QueryString As String) As Object() Implements NextSoftService.INextSoftService.ExecuteSQLNonQuery
            Return MyBase.Channel.ExecuteSQLNonQuery(QueryString)
        End Function
        
        Public Function ExecuteSQLNonQueryAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of Object()) Implements NextSoftService.INextSoftService.ExecuteSQLNonQueryAsync
            Return MyBase.Channel.ExecuteSQLNonQueryAsync(QueryString)
        End Function
        
        Public Function InsertSobrestadia(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As Boolean Implements NextSoftService.INextSoftService.InsertSobrestadia
            Return MyBase.Channel.InsertSobrestadia(oSobrestadiaBE)
        End Function
        
        Public Function InsertSobrestadiaAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean) Implements NextSoftService.INextSoftService.InsertSobrestadiaAsync
            Return MyBase.Channel.InsertSobrestadiaAsync(oSobrestadiaBE)
        End Function
        
        Public Function UpdateSobrestadia(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As Boolean Implements NextSoftService.INextSoftService.UpdateSobrestadia
            Return MyBase.Channel.UpdateSobrestadia(oSobrestadiaBE)
        End Function
        
        Public Function UpdateSobrestadiaAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean) Implements NextSoftService.INextSoftService.UpdateSobrestadiaAsync
            Return MyBase.Channel.UpdateSobrestadiaAsync(oSobrestadiaBE)
        End Function
        
        Public Function DeleteSobrestadia(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As Boolean Implements NextSoftService.INextSoftService.DeleteSobrestadia
            Return MyBase.Channel.DeleteSobrestadia(oSobrestadiaBE)
        End Function
        
        Public Function DeleteSobrestadiaAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean) Implements NextSoftService.INextSoftService.DeleteSobrestadiaAsync
            Return MyBase.Channel.DeleteSobrestadiaAsync(oSobrestadiaBE)
        End Function
        
        Public Function GetAllSobrestadia(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As NextSoftService.COM_Sobrestadia_BE Implements NextSoftService.INextSoftService.GetAllSobrestadia
            Return MyBase.Channel.GetAllSobrestadia(oSobrestadiaBE)
        End Function
        
        Public Function GetAllSobrestadiaAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of NextSoftService.COM_Sobrestadia_BE) Implements NextSoftService.INextSoftService.GetAllSobrestadiaAsync
            Return MyBase.Channel.GetAllSobrestadiaAsync(oSobrestadiaBE)
        End Function
        
        Public Function GetSobrestadiaByFilter(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Data.DataTable Implements NextSoftService.INextSoftService.GetSobrestadiaByFilter
            Return MyBase.Channel.GetSobrestadiaByFilter(oSobrestadiaBE)
        End Function
        
        Public Function GetSobrestadiaByFilterAsync(ByVal oSobrestadiaBE As NextSoftService.COM_Sobrestadia_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements NextSoftService.INextSoftService.GetSobrestadiaByFilterAsync
            Return MyBase.Channel.GetSobrestadiaByFilterAsync(oSobrestadiaBE)
        End Function
        
        Public Function InsertDetSobrestadia(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As Boolean Implements NextSoftService.INextSoftService.InsertDetSobrestadia
            Return MyBase.Channel.InsertDetSobrestadia(oDetSobrestadiaBE)
        End Function
        
        Public Function InsertDetSobrestadiaAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean) Implements NextSoftService.INextSoftService.InsertDetSobrestadiaAsync
            Return MyBase.Channel.InsertDetSobrestadiaAsync(oDetSobrestadiaBE)
        End Function
        
        Public Function UpdateDetSobrestadia(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As Boolean Implements NextSoftService.INextSoftService.UpdateDetSobrestadia
            Return MyBase.Channel.UpdateDetSobrestadia(oDetSobrestadiaBE)
        End Function
        
        Public Function UpdateDetSobrestadiaAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean) Implements NextSoftService.INextSoftService.UpdateDetSobrestadiaAsync
            Return MyBase.Channel.UpdateDetSobrestadiaAsync(oDetSobrestadiaBE)
        End Function
        
        Public Function DeleteDetSobrestadia(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As Boolean Implements NextSoftService.INextSoftService.DeleteDetSobrestadia
            Return MyBase.Channel.DeleteDetSobrestadia(oDetSobrestadiaBE)
        End Function
        
        Public Function DeleteDetSobrestadiaAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of Boolean) Implements NextSoftService.INextSoftService.DeleteDetSobrestadiaAsync
            Return MyBase.Channel.DeleteDetSobrestadiaAsync(oDetSobrestadiaBE)
        End Function
        
        Public Function GetAllDetSobrestadia(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As NextSoftService.COM_DetSobrestadia_BE Implements NextSoftService.INextSoftService.GetAllDetSobrestadia
            Return MyBase.Channel.GetAllDetSobrestadia(oDetSobrestadiaBE)
        End Function
        
        Public Function GetAllDetSobrestadiaAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of NextSoftService.COM_DetSobrestadia_BE) Implements NextSoftService.INextSoftService.GetAllDetSobrestadiaAsync
            Return MyBase.Channel.GetAllDetSobrestadiaAsync(oDetSobrestadiaBE)
        End Function
        
        Public Function GetDetSobrestadiaByFilter(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Data.DataTable Implements NextSoftService.INextSoftService.GetDetSobrestadiaByFilter
            Return MyBase.Channel.GetDetSobrestadiaByFilter(oDetSobrestadiaBE)
        End Function
        
        Public Function GetDetSobrestadiaByFilterAsync(ByVal oDetSobrestadiaBE As NextSoftService.COM_DetSobrestadia_BE) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements NextSoftService.INextSoftService.GetDetSobrestadiaByFilterAsync
            Return MyBase.Channel.GetDetSobrestadiaByFilterAsync(oDetSobrestadiaBE)
        End Function
    End Class
End Namespace
