//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFactDelfin.eFactService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
    public partial class sunatError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private int sunatErrorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int sunatErrorCode {
            get {
                return this.sunatErrorCodeField;
            }
            set {
                this.sunatErrorCodeField = value;
                this.RaisePropertyChanged("sunatErrorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
    public partial class transactionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cdrFileField;
        
        private string digestValueField;
        
        private string identifierField;
        
        private string outStringField;
        
        private byte[] pdfFileField;
        
        private int responseCodeField;
        
        private sunatError sunatErrorField;
        
        private string uuidField;
        
        private byte[] xmlSignedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] cdrFile {
            get {
                return this.cdrFileField;
            }
            set {
                this.cdrFileField = value;
                this.RaisePropertyChanged("cdrFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string digestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
                this.RaisePropertyChanged("digestValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string outString {
            get {
                return this.outStringField;
            }
            set {
                this.outStringField = value;
                this.RaisePropertyChanged("outString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] pdfFile {
            get {
                return this.pdfFileField;
            }
            set {
                this.pdfFileField = value;
                this.RaisePropertyChanged("pdfFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public sunatError sunatError {
            get {
                return this.sunatErrorField;
            }
            set {
                this.sunatErrorField = value;
                this.RaisePropertyChanged("sunatError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=8)]
        public byte[] xmlSigned {
            get {
                return this.xmlSignedField;
            }
            set {
                this.xmlSignedField = value;
                this.RaisePropertyChanged("xmlSigned");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
    public partial class authorization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string passwordField;
        
        private string userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
    public partial class ExecutionException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.connector.alfa1lab.efact/", ConfigurationName="eFactService.TransactionService")]
    public interface TransactionService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje sendPingRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.connector.alfa1lab.efact/TransactionService/sendPingRequest", ReplyAction="http://service.connector.alfa1lab.efact/TransactionService/sendPingResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eFactDelfin.eFactService.sendPingResponse sendPing(eFactDelfin.eFactService.sendPingRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje sendInvoiceRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.connector.alfa1lab.efact/TransactionService/sendInvoiceRequest", ReplyAction="http://service.connector.alfa1lab.efact/TransactionService/sendInvoiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.InterruptedException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendInvoice/Fault/Inte" +
            "rruptedException", Name="InterruptedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.ExecutionException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendInvoice/Fault/Exec" +
            "utionException", Name="ExecutionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eFactDelfin.eFactService.sendInvoiceResponse sendInvoice(eFactDelfin.eFactService.sendInvoiceRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje sendBoletaRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.connector.alfa1lab.efact/TransactionService/sendBoletaRequest", ReplyAction="http://service.connector.alfa1lab.efact/TransactionService/sendBoletaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.InterruptedException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendBoleta/Fault/Inter" +
            "ruptedException", Name="InterruptedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.ExecutionException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendBoleta/Fault/Execu" +
            "tionException", Name="ExecutionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eFactDelfin.eFactService.sendBoletaResponse sendBoleta(eFactDelfin.eFactService.sendBoletaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje sendCreditNoteRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.connector.alfa1lab.efact/TransactionService/sendCreditNoteRequest", ReplyAction="http://service.connector.alfa1lab.efact/TransactionService/sendCreditNoteResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.InterruptedException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendCreditNote/Fault/I" +
            "nterruptedException", Name="InterruptedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.ExecutionException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendCreditNote/Fault/E" +
            "xecutionException", Name="ExecutionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eFactDelfin.eFactService.sendCreditNoteResponse sendCreditNote(eFactDelfin.eFactService.sendCreditNoteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje sendDebitNoteRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.connector.alfa1lab.efact/TransactionService/sendDebitNoteRequest", ReplyAction="http://service.connector.alfa1lab.efact/TransactionService/sendDebitNoteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.InterruptedException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendDebitNote/Fault/In" +
            "terruptedException", Name="InterruptedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.ExecutionException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendDebitNote/Fault/Ex" +
            "ecutionException", Name="ExecutionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eFactDelfin.eFactService.sendDebitNoteResponse sendDebitNote(eFactDelfin.eFactService.sendDebitNoteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje sendVoidedDocumentRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.connector.alfa1lab.efact/TransactionService/sendVoidedDocumentRequ" +
            "est", ReplyAction="http://service.connector.alfa1lab.efact/TransactionService/sendVoidedDocumentResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.InterruptedException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendVoidedDocument/Fau" +
            "lt/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.FaultContractAttribute(typeof(eFactDelfin.eFactService.ExecutionException), Action="http://service.connector.alfa1lab.efact/TransactionService/sendVoidedDocument/Fau" +
            "lt/ExecutionException", Name="ExecutionException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eFactDelfin.eFactService.sendVoidedDocumentResponse sendVoidedDocument(eFactDelfin.eFactService.sendVoidedDocumentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje getStatusRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.connector.alfa1lab.efact/TransactionService/getStatusRequest", ReplyAction="http://service.connector.alfa1lab.efact/TransactionService/getStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eFactDelfin.eFactService.getStatusResponse getStatus(eFactDelfin.eFactService.getStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPing", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendPingRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eFactDelfin.eFactService.authorization Authorization;
        
        public sendPingRequest() {
        }
        
        public sendPingRequest(eFactDelfin.eFactService.authorization Authorization) {
            this.Authorization = Authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendPingResponse", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendPingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool responseSendPing;
        
        public sendPingResponse() {
        }
        
        public sendPingResponse(bool responseSendPing) {
            this.responseSendPing = responseSendPing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendInvoice", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendInvoiceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eFactDelfin.eFactService.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendInvoiceRequest() {
        }
        
        public sendInvoiceRequest(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendInvoiceResponse", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public eFactDelfin.eFactService.transactionResponse[] responseSendInvoice;
        
        public sendInvoiceResponse() {
        }
        
        public sendInvoiceResponse(eFactDelfin.eFactService.transactionResponse[] responseSendInvoice) {
            this.responseSendInvoice = responseSendInvoice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBoleta", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendBoletaRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eFactDelfin.eFactService.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendBoletaRequest() {
        }
        
        public sendBoletaRequest(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendBoletaResponse", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendBoletaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public eFactDelfin.eFactService.transactionResponse[] responseSendBoleta;
        
        public sendBoletaResponse() {
        }
        
        public sendBoletaResponse(eFactDelfin.eFactService.transactionResponse[] responseSendBoleta) {
            this.responseSendBoleta = responseSendBoleta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCreditNote", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendCreditNoteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eFactDelfin.eFactService.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendCreditNoteRequest() {
        }
        
        public sendCreditNoteRequest(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendCreditNoteResponse", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendCreditNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public eFactDelfin.eFactService.transactionResponse[] responseSendCreditNote;
        
        public sendCreditNoteResponse() {
        }
        
        public sendCreditNoteResponse(eFactDelfin.eFactService.transactionResponse[] responseSendCreditNote) {
            this.responseSendCreditNote = responseSendCreditNote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDebitNote", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendDebitNoteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eFactDelfin.eFactService.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendDebitNoteRequest() {
        }
        
        public sendDebitNoteRequest(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendDebitNoteResponse", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendDebitNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public eFactDelfin.eFactService.transactionResponse[] responseSendDebitNote;
        
        public sendDebitNoteResponse() {
        }
        
        public sendDebitNoteResponse(eFactDelfin.eFactService.transactionResponse[] responseSendDebitNote) {
            this.responseSendDebitNote = responseSendDebitNote;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoidedDocument", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendVoidedDocumentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eFactDelfin.eFactService.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public sendVoidedDocumentRequest() {
        }
        
        public sendVoidedDocumentRequest(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            this.Authorization = Authorization;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVoidedDocumentResponse", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class sendVoidedDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public eFactDelfin.eFactService.transactionResponse[] responseSendVoidedDocument;
        
        public sendVoidedDocumentResponse() {
        }
        
        public sendVoidedDocumentResponse(eFactDelfin.eFactService.transactionResponse[] responseSendVoidedDocument) {
            this.responseSendVoidedDocument = responseSendVoidedDocument;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
    public partial class transactionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] cdrFileField;
        
        private string digestValueField;
        
        private string identifierField;
        
        private string messageField;
        
        private string outStringField;
        
        private byte[] pdfFileField;
        
        private string statusField;
        
        private byte[] xmlSignedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] cdrFile {
            get {
                return this.cdrFileField;
            }
            set {
                this.cdrFileField = value;
                this.RaisePropertyChanged("cdrFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string digestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
                this.RaisePropertyChanged("digestValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string outString {
            get {
                return this.outStringField;
            }
            set {
                this.outStringField = value;
                this.RaisePropertyChanged("outString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] pdfFile {
            get {
                return this.pdfFileField;
            }
            set {
                this.pdfFileField = value;
                this.RaisePropertyChanged("pdfFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] xmlSigned {
            get {
                return this.xmlSignedField;
            }
            set {
                this.xmlSignedField = value;
                this.RaisePropertyChanged("xmlSigned");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatus", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class getStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.connector.alfa1lab.efact/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eFactDelfin.eFactService.authorization Authorization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int documentType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string identifier;
        
        public getStatusRequest() {
        }
        
        public getStatusRequest(eFactDelfin.eFactService.authorization Authorization, int documentType, string identifier) {
            this.Authorization = Authorization;
            this.documentType = documentType;
            this.identifier = identifier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusResponse", WrapperNamespace="http://service.connector.alfa1lab.efact/", IsWrapped=true)]
    public partial class getStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public eFactDelfin.eFactService.transactionResult responseSendStatus;
        
        public getStatusResponse() {
        }
        
        public getStatusResponse(eFactDelfin.eFactService.transactionResult responseSendStatus) {
            this.responseSendStatus = responseSendStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionServiceChannel : eFactDelfin.eFactService.TransactionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionServiceClient : System.ServiceModel.ClientBase<eFactDelfin.eFactService.TransactionService>, eFactDelfin.eFactService.TransactionService {
        
        public TransactionServiceClient() {
        }
        
        public TransactionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eFactDelfin.eFactService.sendPingResponse eFactDelfin.eFactService.TransactionService.sendPing(eFactDelfin.eFactService.sendPingRequest request) {
            return base.Channel.sendPing(request);
        }
        
        public bool sendPing(eFactDelfin.eFactService.authorization Authorization) {
            eFactDelfin.eFactService.sendPingRequest inValue = new eFactDelfin.eFactService.sendPingRequest();
            inValue.Authorization = Authorization;
            eFactDelfin.eFactService.sendPingResponse retVal = ((eFactDelfin.eFactService.TransactionService)(this)).sendPing(inValue);
            return retVal.responseSendPing;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eFactDelfin.eFactService.sendInvoiceResponse eFactDelfin.eFactService.TransactionService.sendInvoice(eFactDelfin.eFactService.sendInvoiceRequest request) {
            return base.Channel.sendInvoice(request);
        }
        
        public eFactDelfin.eFactService.transactionResponse[] sendInvoice(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            eFactDelfin.eFactService.sendInvoiceRequest inValue = new eFactDelfin.eFactService.sendInvoiceRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            eFactDelfin.eFactService.sendInvoiceResponse retVal = ((eFactDelfin.eFactService.TransactionService)(this)).sendInvoice(inValue);
            return retVal.responseSendInvoice;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eFactDelfin.eFactService.sendBoletaResponse eFactDelfin.eFactService.TransactionService.sendBoleta(eFactDelfin.eFactService.sendBoletaRequest request) {
            return base.Channel.sendBoleta(request);
        }
        
        public eFactDelfin.eFactService.transactionResponse[] sendBoleta(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            eFactDelfin.eFactService.sendBoletaRequest inValue = new eFactDelfin.eFactService.sendBoletaRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            eFactDelfin.eFactService.sendBoletaResponse retVal = ((eFactDelfin.eFactService.TransactionService)(this)).sendBoleta(inValue);
            return retVal.responseSendBoleta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eFactDelfin.eFactService.sendCreditNoteResponse eFactDelfin.eFactService.TransactionService.sendCreditNote(eFactDelfin.eFactService.sendCreditNoteRequest request) {
            return base.Channel.sendCreditNote(request);
        }
        
        public eFactDelfin.eFactService.transactionResponse[] sendCreditNote(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            eFactDelfin.eFactService.sendCreditNoteRequest inValue = new eFactDelfin.eFactService.sendCreditNoteRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            eFactDelfin.eFactService.sendCreditNoteResponse retVal = ((eFactDelfin.eFactService.TransactionService)(this)).sendCreditNote(inValue);
            return retVal.responseSendCreditNote;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eFactDelfin.eFactService.sendDebitNoteResponse eFactDelfin.eFactService.TransactionService.sendDebitNote(eFactDelfin.eFactService.sendDebitNoteRequest request) {
            return base.Channel.sendDebitNote(request);
        }
        
        public eFactDelfin.eFactService.transactionResponse[] sendDebitNote(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            eFactDelfin.eFactService.sendDebitNoteRequest inValue = new eFactDelfin.eFactService.sendDebitNoteRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            eFactDelfin.eFactService.sendDebitNoteResponse retVal = ((eFactDelfin.eFactService.TransactionService)(this)).sendDebitNote(inValue);
            return retVal.responseSendDebitNote;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eFactDelfin.eFactService.sendVoidedDocumentResponse eFactDelfin.eFactService.TransactionService.sendVoidedDocument(eFactDelfin.eFactService.sendVoidedDocumentRequest request) {
            return base.Channel.sendVoidedDocument(request);
        }
        
        public eFactDelfin.eFactService.transactionResponse[] sendVoidedDocument(eFactDelfin.eFactService.authorization Authorization, byte[] file) {
            eFactDelfin.eFactService.sendVoidedDocumentRequest inValue = new eFactDelfin.eFactService.sendVoidedDocumentRequest();
            inValue.Authorization = Authorization;
            inValue.file = file;
            eFactDelfin.eFactService.sendVoidedDocumentResponse retVal = ((eFactDelfin.eFactService.TransactionService)(this)).sendVoidedDocument(inValue);
            return retVal.responseSendVoidedDocument;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eFactDelfin.eFactService.getStatusResponse eFactDelfin.eFactService.TransactionService.getStatus(eFactDelfin.eFactService.getStatusRequest request) {
            return base.Channel.getStatus(request);
        }
        
        public eFactDelfin.eFactService.transactionResult getStatus(eFactDelfin.eFactService.authorization Authorization, int documentType, string identifier) {
            eFactDelfin.eFactService.getStatusRequest inValue = new eFactDelfin.eFactService.getStatusRequest();
            inValue.Authorization = Authorization;
            inValue.documentType = documentType;
            inValue.identifier = identifier;
            eFactDelfin.eFactService.getStatusResponse retVal = ((eFactDelfin.eFactService.TransactionService)(this)).getStatus(inValue);
            return retVal.responseSendStatus;
        }
    }
}
