//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delfin.Comercial.NextSoftService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="COM_Sobrestadia_BE", Namespace="http://schemas.datacontract.org/2004/07/Application.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class COM_Sobrestadia_BE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CONT_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ENTC_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SOES_ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SOES_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SOES_FecFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SOES_FecIniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOES_ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOES_ServiceContractField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CONT_Codigo {
            get {
                return this.CONT_CodigoField;
            }
            set {
                if ((this.CONT_CodigoField.Equals(value) != true)) {
                    this.CONT_CodigoField = value;
                    this.RaisePropertyChanged("CONT_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ENTC_Codigo {
            get {
                return this.ENTC_CodigoField;
            }
            set {
                if ((this.ENTC_CodigoField.Equals(value) != true)) {
                    this.ENTC_CodigoField = value;
                    this.RaisePropertyChanged("ENTC_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SOES_Activo {
            get {
                return this.SOES_ActivoField;
            }
            set {
                if ((this.SOES_ActivoField.Equals(value) != true)) {
                    this.SOES_ActivoField = value;
                    this.RaisePropertyChanged("SOES_Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SOES_Codigo {
            get {
                return this.SOES_CodigoField;
            }
            set {
                if ((this.SOES_CodigoField.Equals(value) != true)) {
                    this.SOES_CodigoField = value;
                    this.RaisePropertyChanged("SOES_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SOES_FecFin {
            get {
                return this.SOES_FecFinField;
            }
            set {
                if ((this.SOES_FecFinField.Equals(value) != true)) {
                    this.SOES_FecFinField = value;
                    this.RaisePropertyChanged("SOES_FecFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SOES_FecIni {
            get {
                return this.SOES_FecIniField;
            }
            set {
                if ((this.SOES_FecIniField.Equals(value) != true)) {
                    this.SOES_FecIniField = value;
                    this.RaisePropertyChanged("SOES_FecIni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SOES_Observaciones {
            get {
                return this.SOES_ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.SOES_ObservacionesField, value) != true)) {
                    this.SOES_ObservacionesField = value;
                    this.RaisePropertyChanged("SOES_Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SOES_ServiceContract {
            get {
                return this.SOES_ServiceContractField;
            }
            set {
                if ((object.ReferenceEquals(this.SOES_ServiceContractField, value) != true)) {
                    this.SOES_ServiceContractField = value;
                    this.RaisePropertyChanged("SOES_ServiceContract");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="COM_DetSobrestadia_BE", Namespace="http://schemas.datacontract.org/2004/07/Application.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class COM_DetSobrestadia_BE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PACK_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PUER_CodDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SOES_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SOES_DiasSobrestadiaClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short SOES_DiasSobrestadiaLineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SOES_ItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PACK_Codigo {
            get {
                return this.PACK_CodigoField;
            }
            set {
                if ((this.PACK_CodigoField.Equals(value) != true)) {
                    this.PACK_CodigoField = value;
                    this.RaisePropertyChanged("PACK_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PUER_CodDestino {
            get {
                return this.PUER_CodDestinoField;
            }
            set {
                if ((this.PUER_CodDestinoField.Equals(value) != true)) {
                    this.PUER_CodDestinoField = value;
                    this.RaisePropertyChanged("PUER_CodDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SOES_Codigo {
            get {
                return this.SOES_CodigoField;
            }
            set {
                if ((this.SOES_CodigoField.Equals(value) != true)) {
                    this.SOES_CodigoField = value;
                    this.RaisePropertyChanged("SOES_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SOES_DiasSobrestadiaCliente {
            get {
                return this.SOES_DiasSobrestadiaClienteField;
            }
            set {
                if ((this.SOES_DiasSobrestadiaClienteField.Equals(value) != true)) {
                    this.SOES_DiasSobrestadiaClienteField = value;
                    this.RaisePropertyChanged("SOES_DiasSobrestadiaCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short SOES_DiasSobrestadiaLinea {
            get {
                return this.SOES_DiasSobrestadiaLineaField;
            }
            set {
                if ((this.SOES_DiasSobrestadiaLineaField.Equals(value) != true)) {
                    this.SOES_DiasSobrestadiaLineaField = value;
                    this.RaisePropertyChanged("SOES_DiasSobrestadiaLinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SOES_Item {
            get {
                return this.SOES_ItemField;
            }
            set {
                if ((this.SOES_ItemField.Equals(value) != true)) {
                    this.SOES_ItemField = value;
                    this.RaisePropertyChanged("SOES_Item");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NextSoftService.INextSoftService")]
    public interface INextSoftService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/ExecuteSQL", ReplyAction="http://tempuri.org/INextSoftService/ExecuteSQLResponse")]
        System.Data.DataSet ExecuteSQL(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/ExecuteSQLNonQuery", ReplyAction="http://tempuri.org/INextSoftService/ExecuteSQLNonQueryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] ExecuteSQLNonQuery(string QueryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/InsertSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/InsertSobrestadiaResponse")]
        bool InsertSobrestadia(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE oSobrestadiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/UpdateSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/UpdateSobrestadiaResponse")]
        bool UpdateSobrestadia(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE oSobrestadiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/DeleteSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/DeleteSobrestadiaResponse")]
        bool DeleteSobrestadia(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE oSobrestadiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/GetAllSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/GetAllSobrestadiaResponse")]
        Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE GetAllSobrestadia(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE oSobrestadiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/GetAllDataTableSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/GetAllDataTableSobrestadiaResponse")]
        System.Data.DataTable GetAllDataTableSobrestadia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/InsertDetSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/InsertDetSobrestadiaResponse")]
        bool InsertDetSobrestadia(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE oDetSobrestadiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/UpdateDetSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/UpdateDetSobrestadiaResponse")]
        bool UpdateDetSobrestadia(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE oDetSobrestadiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/DeleteDetSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/DeleteDetSobrestadiaResponse")]
        bool DeleteDetSobrestadia(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE oDetSobrestadiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/GetAllDetSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/GetAllDetSobrestadiaResponse")]
        Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE GetAllDetSobrestadia(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE oDetSobrestadiaBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INextSoftService/GetAllDataTableDetSobrestadia", ReplyAction="http://tempuri.org/INextSoftService/GetAllDataTableDetSobrestadiaResponse")]
        System.Data.DataTable GetAllDataTableDetSobrestadia();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INextSoftServiceChannel : Delfin.Comercial.NextSoftService.INextSoftService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NextSoftServiceClient : System.ServiceModel.ClientBase<Delfin.Comercial.NextSoftService.INextSoftService>, Delfin.Comercial.NextSoftService.INextSoftService {
        
        public NextSoftServiceClient() {
        }
        
        public NextSoftServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NextSoftServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NextSoftServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NextSoftServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ExecuteSQL(string QueryString) {
            return base.Channel.ExecuteSQL(QueryString);
        }
        
        public object[] ExecuteSQLNonQuery(string QueryString) {
            return base.Channel.ExecuteSQLNonQuery(QueryString);
        }
        
        public bool InsertSobrestadia(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE oSobrestadiaBE) {
            return base.Channel.InsertSobrestadia(oSobrestadiaBE);
        }
        
        public bool UpdateSobrestadia(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE oSobrestadiaBE) {
            return base.Channel.UpdateSobrestadia(oSobrestadiaBE);
        }
        
        public bool DeleteSobrestadia(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE oSobrestadiaBE) {
            return base.Channel.DeleteSobrestadia(oSobrestadiaBE);
        }
        
        public Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE GetAllSobrestadia(Delfin.Comercial.NextSoftService.COM_Sobrestadia_BE oSobrestadiaBE) {
            return base.Channel.GetAllSobrestadia(oSobrestadiaBE);
        }
        
        public System.Data.DataTable GetAllDataTableSobrestadia() {
            return base.Channel.GetAllDataTableSobrestadia();
        }
        
        public bool InsertDetSobrestadia(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE oDetSobrestadiaBE) {
            return base.Channel.InsertDetSobrestadia(oDetSobrestadiaBE);
        }
        
        public bool UpdateDetSobrestadia(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE oDetSobrestadiaBE) {
            return base.Channel.UpdateDetSobrestadia(oDetSobrestadiaBE);
        }
        
        public bool DeleteDetSobrestadia(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE oDetSobrestadiaBE) {
            return base.Channel.DeleteDetSobrestadia(oDetSobrestadiaBE);
        }
        
        public Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE GetAllDetSobrestadia(Delfin.Comercial.NextSoftService.COM_DetSobrestadia_BE oDetSobrestadiaBE) {
            return base.Channel.GetAllDetSobrestadia(oDetSobrestadiaBE);
        }
        
        public System.Data.DataTable GetAllDataTableDetSobrestadia() {
            return base.Channel.GetAllDataTableDetSobrestadia();
        }
    }
}
